title   Zohara OS (Linux-Zen)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-zen
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=%INSTALL_DIR% archisolabel=ZOHARA_ISO rd.systemd.gpt_auto=0
