i18n:
  name: "Installing base system with pacstrap"

dontChroot: true
timeout: 3600
script:
  - "-pacstrap -K /tmp/calamares-root- base base-devel linux-zen linux-zen-headers linux-firmware mkinitcpio networkmanager sddm xorg-server wayland grub efibootmgr"
